name: Smoke-Test Fuzz Targets

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  fuzz:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    env:
      FUZZ_TIME: 600
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
        fuzz_target:
          - parse
          - parse_structured
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-windows
        if: runner.os == 'Windows'
        with:
          asan: true
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1.3.0
        with:
          channel: nightly
          bins: cargo-fuzz
      - run: cargo fuzz build ${{ matrix.fuzz_target }} --target ${{ matrix.target }}
      - run: cargo fuzz run ${{ matrix.fuzz_target }} --target ${{ matrix.target }} -- -max_total_time=${{ env.FUZZ_TIME }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: fuzzing-artifacts-${{ matrix.fuzz_target }}-${{ github.sha }}
          path: fuzz/artifacts
